// Generated by https://quicktype.io

export interface PokemonListResponse {
    count:    number;
    next:     string;
    previous: string;
    results:  BasicInfo[];
}

export interface BasicInfo {
    name: string;
    url:  string;
}
